<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Be.Vlaanderen.Basisregisters.Api" Version="27.0.0" />
        <PackageVersion Include="Be.Vlaanderen.Basisregisters.NisCodeService.Abstractions" Version="7.0.0" />

        <PackageVersion Include="Microsoft.AspNetCore.Authorization" Version="10.0.8" />
        <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
        <PackageVersion Include="Duende.AspNetCore.Authentication.OAuth2Introspection" Version="7.0.1" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />

        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
        <PackageVersion Include="xunit" Version="2.9.3" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
        <PackageVersion Include="FluentAssertions" Version="[7.1.0,8.0.0)" />
        <PackageVersion Include="Be.Vlaanderen.Basisregisters.DockerUtilities" Version="4.1.0" />
        <PackageVersion Include="Moq" Version="4.20.72" />
        <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.8" />
        <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="10.0.8" />

        <PackageVersion Include="SourceLink.Embed.AllSourceFiles" Version="2.8.3" />
        <PackageVersion Include="SourceLink.Copy.PdbFiles" Version="2.8.3" />
    </ItemGroup>
</Project>
