version: '3'
services:
   acmidm:
     image: ghcr.io/informatievlaanderen/identity-server-fake:033d00a
     volumes:
       - ./identityserver:/home/identityserver
     ports:
       - "5051:80"
     environment:
       IdentityServer__ConfigFolder: /home/identityserver